# Generated by Django 4.1.5 on 2023-01-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_ts', models.DateTimeField()),
                ('title', models.CharField(max_length=400)),
                ('content', models.TextField(blank=True, null=True, verbose_name='text')),
            ],
        ),
    ]
